name: Discord Release Notification

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify_discord:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Discord Webhook Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            A new release has been published!
            **Name:** ${{ github.event.release.name }}
            **URL:** ${{ github.event.release.html_url }}

            **Description:**
            ${{ github.event.release.body }}

      - name: Debug Information
        if: failure()
        run: |
          echo "Workflow failed. Debug information:"
          echo "Event name: ${{ github.event_name }}"
          echo "Release name: ${{ github.event.release.name }}"
          echo "Release URL: ${{ github.event.release.html_url }}"
          echo "First 500 characters of release body:"
          echo "${{ github.event.release.body }}" | cut -c 1-500
