name: Update GitHub Pages Redirection

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-redirect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest release asset URLs
        id: get_urls
        run: |
          RESPONSE=$(curl -s https://api.github.com/repos/McSon2/ssp_shuffles/releases/latest)
          WINDOWS_URL=$(echo "$RESPONSE" | grep browser_download_url | grep .exe | head -n 1 | cut -d '"' -f 4)
          MAC_URL=$(echo "$RESPONSE" | grep browser_download_url | grep .dmg | head -n 1 | cut -d '"' -f 4)
          echo "WINDOWS_URL=$WINDOWS_URL" >> $GITHUB_ENV
          echo "MAC_URL=$MAC_URL" >> $GITHUB_ENV

      - name: Generate HTML files
        run: |
          mkdir -p deploy/win
          mkdir -p deploy/mac
          
          # Création de la page d'accueil
          cat > deploy/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
              <title>Télécharger SSP</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      text-align: center;
                      padding: 50px;
                  }
                  .download-buttons {
                      margin-top: 20px;
                  }
                  .button {
                      display: inline-block;
                      padding: 10px 20px;
                      margin: 10px;
                      background-color: #007bff;
                      color: white;
                      text-decoration: none;
                      border-radius: 5px;
                  }
              </style>
          </head>
          <body>
              <h1>Télécharger SSP</h1>
              <p>Choisissez votre système d'exploitation :</p>
              <div class="download-buttons">
                  <a href="win" class="button">Windows</a>
                  <a href="mac" class="button">Mac</a>
              </div>
          </body>
          </html>
          EOF
          
          # Création du fichier Windows
          cat > deploy/win/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="refresh" content="0; url=${WINDOWS_URL}" />
            <title>Redirection Windows</title>
          </head>
          <body>
            <p>Redirection en cours vers le téléchargement de la version Windows...</p>
          </body>
          </html>
          EOF
          
          # Création du fichier Mac
          cat > deploy/mac/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="refresh" content="0; url=${MAC_URL}" />
            <title>Redirection Mac</title>
          </head>
          <body>
            <p>Redirection en cours vers le téléchargement de la version Mac...</p>
          </body>
          </html>
          EOF

      - name: Verify files
        run: |
          echo "Structure des dossiers :"
          ls -R deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
          allow_empty_commit: true
          commit_message: "Mise à jour des redirections vers la dernière release"
